In [1]:
import pandas as pd
import requests
import json

In [2]:
api_key = 'DLGaXUfyqpAyVVOInE08AcMkOdYGFlsk' 
stores_symbols = ['AAPL', 'GOOGL', 'MSFT', 'META']
symbols_string = ','.join(stores_symbols)
base_url = 'https://financialmodelingprep.com/api/v3/historical-price-full/'
full_url = f"{base_url}{symbols_string}?apikey={api_key}"
response = requests.get(full_url)
response.status_code

200

In [3]:
data = response.json()
print(json.dumps(data, indent=2))

{
  "historicalStockList": [
    {
      "symbol": "AAPL",
      "historical": [
        {
          "date": "2025-05-29",
          "open": 203.575,
          "high": 203.78,
          "low": 198.56,
          "close": 199.64,
          "adjClose": 199.64,
          "volume": 25584723,
          "unadjustedVolume": 25584723,
          "change": -3.94,
          "changePercent": -1.93295,
          "vwap": 200.66,
          "label": "May 29, 25",
          "changeOverTime": -0.0193295
        },
        {
          "date": "2025-05-28",
          "open": 200.59,
          "high": 202.73,
          "low": 199.9,
          "close": 200.42,
          "adjClose": 200.42,
          "volume": 45339678,
          "unadjustedVolume": 45339678,
          "change": -0.17,
          "changePercent": -0.08474999,
          "vwap": 200.91,
          "label": "May 28, 25",
          "changeOverTime": -0.0008474999
        },
        {
          "date": "2025-05-27",
          "open": 198.3,
          "high": 200.74,
          "low": 197.43,
          "close": 200.21,
          "adjClose": 200.21,
          "volume": 56288500,
          "unadjustedVolume": 56288500,
          "change": 1.91,
          "changePercent": 0.96319,
          "vwap": 199.17,
          "label": "May 27, 25",
          "changeOverTime": 0.0096319
        },
        {
          "date": "2025-05-23",
          "open": 193.67,
          "high": 197.7,
          "low": 193.46,
          "close": 195.27,
          "adjClose": 195.27,
          "volume": 78432918,
          "unadjustedVolume": 78432918,
          "change": 1.61,
          "changePercent": 0.82615,
          "vwap": 195.025,
          "label": "May 23, 25",
          "changeOverTime": 0.0082615
        },
        {
          "date": "2025-05-22",
          "open": 200.71,
          "high": 202.75,
          "low": 199.7,
          "close": 201.36,
          "adjClose": 201.36,
          "volume": 46742407,
          "unadjustedVolume": 46742407,
          "change": 0.65,
          "changePercent": 0.32385,
          "vwap": 201.13,
          "label": "May 22, 25",
          "changeOverTime": 0.0032385
        },
        {
          "date": "2025-05-21",
          "open": 205.17,
          "high": 207.04,
          "low": 200.71,
          "close": 202.09,
          "adjClose": 202.09,
          "volume": 59211800,
          "unadjustedVolume": 59211800,
          "change": -3.08,
          "changePercent": -1.5,
          "vwap": 203.7525,
          "label": "May 21, 25",
          "changeOverTime": -0.015
        },
        {
          "date": "2025-05-20",
          "open": 207.67,
          "high": 208.47,
          "low": 205.03,
          "close": 206.86,
          "adjClose": 206.86,
          "volume": 42496635,
          "unadjustedVolume": 42496635,
          "change": -0.81,
          "changePercent": -0.39004,
          "vwap": 207.0075,
          "label": "May 20, 25",
          "changeOverTime": -0.0039004
        },
        {
          "date": "2025-05-19",
          "open": 207.91,
          "high": 209.48,
          "low": 204.26,
          "close": 208.78,
          "adjClose": 208.78,
          "volume": 46140527,
          "unadjustedVolume": 46140527,
          "change": 0.87,
          "changePercent": 0.41845,
          "vwap": 207.6075,
          "label": "May 19, 25",
          "changeOverTime": 0.0041845
        },
        {
          "date": "2025-05-16",
          "open": 212.36,
          "high": 212.57,
          "low": 209.77,
          "close": 211.26,
          "adjClose": 211.26,
          "volume": 54737900,
          "unadjustedVolume": 54737900,
          "change": -1.1,
          "changePercent": -0.51799,
          "vwap": 211.49,
          "label": "May 16, 25",
          "changeOverTime": -0.0051799
        },
        {
          "date": "2025-05-15",
          "open": 210.95,
          "high": 212.96,
          "low": 209.54,
          "close": 211.45,
          "adjClose": 211.45,
          "volume": 45029500,
          "unadjustedVolume": 45029500,
          "change": 0.5,
          "changePercent": 0.23702,
          "vwap": 211.225,
          "label": "May 15, 25",
          "changeOverTime": 0.0023702
        },
        {
          "date": "2025-05-14",
          "open": 212.43,
          "high": 213.94,
          "low": 210.58,
          "close": 212.33,
          "adjClose": 212.33,
          "volume": 49325825,
          "unadjustedVolume": 49325825,
          "change": -0.1,
          "changePercent": -0.04707433,
          "vwap": 212.32,
          "label": "May 14, 25",
          "changeOverTime": -0.0004707433
        },
        {
          "date": "2025-05-13",
          "open": 210.43,
          "high": 213.4,
          "low": 209,
          "close": 212.93,
          "adjClose": 212.93,
          "volume": 51909332,
          "unadjustedVolume": 51909332,
          "change": 2.5,
          "changePercent": 1.19,
          "vwap": 211.44,
          "label": "May 13, 25",
          "changeOverTime": 0.0119
        },
        {
          "date": "2025-05-12",
          "open": 210.97,
          "high": 211.27,
          "low": 206.75,
          "close": 210.79,
          "adjClose": 210.79,
          "volume": 63775814,
          "unadjustedVolume": 63775814,
          "change": -0.18,
          "changePercent": -0.08532019,
          "vwap": 209.945,
          "label": "May 12, 25",
          "changeOverTime": -0.0008532019
        },
        {
          "date": "2025-05-09",
          "open": 199,
          "high": 200.54,
          "low": 197.54,
          "close": 198.53,
          "adjClose": 198.27,
          "volume": 36453923,
          "unadjustedVolume": 36453923,
          "change": -0.47,
          "changePercent": -0.23618,
          "vwap": 198.9025,
          "label": "May 09, 25",
          "changeOverTime": -0.0023618
        },
        {
          "date": "2025-05-08",
          "open": 197.72,
          "high": 200.05,
          "low": 194.68,
          "close": 197.49,
          "adjClose": 197.23,
          "volume": 50478900,
          "unadjustedVolume": 50478900,
          "change": -0.23,
          "changePercent": -0.11633,
          "vwap": 197.485,
          "label": "May 08, 25",
          "changeOverTime": -0.0011633
        },
        {
          "date": "2025-05-07",
          "open": 199.17,
          "high": 199.44,
          "low": 193.25,
          "close": 196.25,
          "adjClose": 195.99,
          "volume": 68616943,
          "unadjustedVolume": 68616943,
          "change": -2.92,
          "changePercent": -1.47,
          "vwap": 197.0275,
          "label": "May 07, 25",
          "changeOverTime": -0.0147
        },
        {
          "date": "2025-05-06",
          "open": 198.21,
          "high": 200.65,
          "low": 197.02,
          "close": 198.51,
          "adjClose": 198.25,
          "volume": 51216500,
          "unadjustedVolume": 51216500,
          "change": 0.3,
          "changePercent": 0.15135,
          "vwap": 198.5975,
          "label": "May 06, 25",
          "changeOverTime": 0.0015135
        },
        {
          "date": "2025-05-05",
          "open": 203.1,
          "high": 204.1,
          "low": 198.21,
          "close": 198.89,
          "adjClose": 198.63,
          "volume": 69018500,
          "unadjustedVolume": 69018500,
          "change": -4.21,
          "changePercent": -2.07,
          "vwap": 201.075,
          "label": "May 05, 25",
          "changeOverTime": -0.0207
        },
        {
          "date": "2025-05-02",
          "open": 206.09,
          "high": 206.99,
          "low": 202.16,
          "close": 205.35,
          "adjClose": 205.08,
          "volume": 101010621,
          "unadjustedVolume": 101010621,
          "change": -0.74,
          "changePercent": -0.35907,
          "vwap": 205.1475,
          "label": "May 02, 25",
          "changeOverTime": -0.0035907
        },
        {
          "date": "2025-05-01",
          "open": 209.08,
          "high": 214.56,
          "low": 208.9,
          "close": 213.32,
          "adjClose": 213.04,
          "volume": 57365700,
          "unadjustedVolume": 57365700,
          "change": 4.24,
          "changePercent": 2.03,
          "vwap": 211.465,
          "label": "May 01, 25",
          "changeOverTime": 0.0203
        },
        {
          "date": "2025-04-30",
          "open": 209.3,
          "high": 213.58,
          "low": 206.67,
          "close": 212.5,
          "adjClose": 212.22,
          "volume": 52286500,
          "unadjustedVolume": 52286500,
          "change": 3.2,
          "changePercent": 1.53,
          "vwap": 210.5125,
          "label": "April 30, 25",
          "changeOverTime": 0.0153
        },
        {
          "date": "2025-04-29",
          "open": 208.69,
          "high": 212.24,
          "low": 208.37,
          "close": 211.21,
          "adjClose": 210.93,
          "volume": 36827633,
          "unadjustedVolume": 36827633,
          "change": 2.52,
          "changePercent": 1.21,
          "vwap": 210.1275,
          "label": "April 29, 25",
          "changeOverTime": 0.0121
        },
        {
          "date": "2025-04-28",
          "open": 210,
          "high": 211.5,
          "low": 207.46,
          "close": 210.14,
          "adjClose": 209.86,
          "volume": 38743100,
          "unadjustedVolume": 38743100,
          "change": 0.14,
          "changePercent": 0.06666667,
          "vwap": 209.775,
          "label": "April 28, 25",
          "changeOverTime": 0.0006666667
        },
        {
          "date": "2025-04-25",
          "open": 206.37,
          "high": 209.75,
          "low": 206.2,
          "close": 209.28,
          "adjClose": 209.01,
          "volume": 38222300,
          "unadjustedVolume": 38222300,
          "change": 2.91,
          "changePercent": 1.41,
          "vwap": 207.9,
          "label": "April 25, 25",
          "changeOverTime": 0.0141
        },
        {
          "date": "2025-04-24",
          "open": 204.89,
          "high": 208.83,
          "low": 202.94,
          "close": 208.37,
          "adjClose": 208.1,
          "volume": 47311000,
          "unadjustedVolume": 47311000,
          "change": 3.48,
          "changePercent": 1.7,
          "vwap": 206.2575,
          "label": "April 24, 25",
          "changeOverTime": 0.017
        },
        {
          "date": "2025-04-23",
          "open": 206,
          "high": 208,
          "low": 202.8,
          "close": 204.6,
          "adjClose": 204.33,
          "volume": 52929200,
          "unadjustedVolume": 52929200,
          "change": -1.4,
          "changePercent": -0.67961,
          "vwap": 205.35,
          "label": "April 23, 25",
          "changeOverTime": -0.0067961
        },
        {
          "date": "2025-04-22",
          "open": 196.12,
          "high": 201.59,
          "low": 195.97,
          "close": 199.74,
          "adjClose": 199.48,
          "volume": 52976400,
          "unadjustedVolume": 52976400,
          "change": 3.62,
          "changePercent": 1.85,
          "vwap": 198.355,
          "label": "April 22, 25",
          "changeOverTime": 0.0185
        },
        {
          "date": "2025-04-21",
          "open": 193.27,
          "high": 193.8,
          "low": 189.81,
          "close": 193.16,
          "adjClose": 192.91,
          "volume": 46742537,
          "unadjustedVolume": 46742537,
          "change": -0.105,
          "changePercent": -0.0569152,
          "vwap": 192.51,
          "label": "April 21, 25",
          "changeOverTime": -0.000569152
        },
        {
          "date": "2025-04-17",
          "open": 197.2,
          "high": 198.83,
          "low": 194.42,
          "close": 196.98,
          "adjClose": 196.72,
          "volume": 52164675,
          "unadjustedVolume": 52164675,
          "change": -0.22,
          "changePercent": -0.11156,
          "vwap": 196.8575,
          "label": "April 17, 25",
          "changeOverTime": -0.0011156
        },
        {
          "date": "2025-04-16",
          "open": 198.36,
          "high": 200.7,
          "low": 192.37,
          "close": 194.27,
          "adjClose": 194.02,
          "volume": 59732423,
          "unadjustedVolume": 59732423,
          "change": -4.09,
          "changePercent": -2.06,
          "vwap": 196.425,
          "label": "April 16, 25",
          "changeOverTime": -0.0206
        },
        {
          "date": "2025-04-15",
          "open": 201.86,
          "high": 203.51,
          "low": 199.8,
          "close": 202.14,
          "adjClose": 201.88,
          "volume": 51343900,
          "unadjustedVolume": 51343900,
          "change": 0.285,
          "changePercent": 0.13871,
          "vwap": 201.8275,
          "label": "April 15, 25",
          "changeOverTime": 0.0013871
        },
        {
          "date": "2025-04-14",
          "open": 211.44,
          "high": 212.94,
          "low": 201.16,
          "close": 202.52,
          "adjClose": 202.25,
          "volume": 101352911,
          "unadjustedVolume": 101352911,
          "change": -8.92,
          "changePercent": -4.22,
          "vwap": 207.015,
          "label": "April 14, 25",
          "changeOverTime": -0.0422
        },
        {
          "date": "2025-04-11",
          "open": 186.1,
          "high": 199.54,
          "low": 186.06,
          "close": 198.15,
          "adjClose": 197.89,
          "volume": 87435915,
          "unadjustedVolume": 87435915,
          "change": 12.05,
          "changePercent": 6.48,
          "vwap": 192.4625,
          "label": "April 11, 25",
          "changeOverTime": 0.0648
        },
        {
          "date": "2025-04-10",
          "open": 189.07,
          "high": 194.78,
          "low": 183,
          "close": 190.42,
          "adjClose": 190.17,
          "volume": 121880000,
          "unadjustedVolume": 121880000,
          "change": 1.35,
          "changePercent": 0.71402,
          "vwap": 189.3175,
          "label": "April 10, 25",
          "changeOverTime": 0.0071402
        },
        {
          "date": "2025-04-09",
          "open": 171.95,
          "high": 200.61,
          "low": 171.89,
          "close": 198.85,
          "adjClose": 198.59,
          "volume": 184395900,
          "unadjustedVolume": 184395900,
          "change": 26.9,
          "changePercent": 15.64,
          "vwap": 185.825,
          "label": "April 09, 25",
          "changeOverTime": 0.1564
        },
        {
          "date": "2025-04-08",
          "open": 186.7,
          "high": 190.34,
          "low": 169.21,
          "close": 172.42,
          "adjClose": 172.19,
          "volume": 120859500,
          "unadjustedVolume": 120859500,
          "change": -14.28,
          "changePercent": -7.65,
          "vwap": 179.6675,
          "label": "April 08, 25",
          "changeOverTime": -0.0765
        },
        {
          "date": "2025-04-07",
          "open": 177.2,
          "high": 194.15,
          "low": 174.62,
          "close": 181.46,
          "adjClose": 181.22,
          "volume": 160466300,
          "unadjustedVolume": 160466300,
          "change": 4.26,
          "changePercent": 2.4,
          "vwap": 181.8575,
          "label": "April 07, 25",
          "changeOverTime": 0.024
        },
        {
          "date": "2025-04-04",
          "open": 193.89,
          "high": 199.88,
          "low": 187.34,
          "close": 188.38,
          "adjClose": 188.13,
          "volume": 125910913,
          "unadjustedVolume": 125910913,
          "change": -5.51,
          "changePercent": -2.84,
          "vwap": 192.3725,
          "label": "April 04, 25",
          "changeOverTime": -0.0284
        },
        {
          "date": "2025-04-03",
          "open": 205.54,
          "high": 207.49,
          "low": 201.25,
          "close": 203.19,
          "adjClose": 202.92,
          "volume": 103419006,
          "unadjustedVolume": 103419006,
          "change": -2.35,
          "changePercent": -1.14,
          "vwap": 204.3675,
          "label": "April 03, 25",
          "changeOverTime": -0.0114
        },
        {
          "date": "2025-04-02",
          "open": 221.32,
          "high": 225.19,
          "low": 221.02,
          "close": 223.89,
          "adjClose": 223.6,
          "volume": 35905904,
          "unadjustedVolume": 35905904,
          "change": 2.57,
          "changePercent": 1.16,
          "vwap": 222.855,
          "label": "April 02, 25",
          "changeOverTime": 0.0116
        },
        {
          "date": "2025-04-01",
          "open": 219.81,
          "high": 223.68,
          "low": 218.9,
          "close": 223.19,
          "adjClose": 222.9,
          "volume": 36412740,
          "unadjustedVolume": 36412740,
          "change": 3.38,
          "changePercent": 1.54,
          "vwap": 221.395,
          "label": "April 01, 25",
          "changeOverTime": 0.0154
        },
        {
          "date": "2025-03-31",
          "open": 217.01,
          "high": 225.62,
          "low": 216.23,
          "close": 222.13,
          "adjClose": 221.84,
          "volume": 65299321,
          "unadjustedVolume": 65299321,
          "change": 5.13,
          "changePercent": 2.36,
          "vwap": 220.2475,
          "label": "March 31, 25",
          "changeOverTime": 0.0236
        },
        {
          "date": "2025-03-28",
          "open": 221.67,
          "high": 223.81,
          "low": 217.68,
          "close": 217.9,
          "adjClose": 217.61,
          "volume": 39818617,
          "unadjustedVolume": 39818617,
          "change": -3.77,
          "changePercent": -1.7,
          "vwap": 220.265,
          "label": "March 28, 25",
          "changeOverTime": -0.017
        },
        {
          "date": "2025-03-27",
          "open": 221.39,
          "high": 224.99,
          "low": 220.56,
          "close": 223.85,
          "adjClose": 223.56,
          "volume": 37094800,
          "unadjustedVolume": 37094800,
          "change": 2.46,
          "changePercent": 1.11,
          "vwap": 222.6975,
          "label": "March 27, 25",
          "changeOverTime": 0.0111
        },
        {
          "date": "2025-03-26",
          "open": 223.51,
          "high": 225.02,
          "low": 220.47,
          "close": 221.53,
          "adjClose": 221.24,
          "volume": 34532656,
          "unadjustedVolume": 34532656,
          "change": -1.98,
          "changePercent": -0.88587,
          "vwap": 222.6325,
          "label": "March 26, 25",
          "changeOverTime": -0.0088587
        },
        {
          "date": "2025-03-25",
          "open": 220.77,
          "high": 224.1,
          "low": 220.08,
          "close": 223.75,
          "adjClose": 223.46,
          "volume": 34493600,
          "unadjustedVolume": 34493600,
          "change": 2.98,
          "changePercent": 1.35,
          "vwap": 222.175,
          "label": "March 25, 25",
          "changeOverTime": 0.0135
        },
        {
          "date": "2025-03-24",
          "open": 221,
          "high": 221.48,
          "low": 218.58,
          "close": 220.73,
          "adjClose": 220.44,
          "volume": 44299500,
          "unadjustedVolume": 44299500,
          "change": -0.27,
          "changePercent": -0.12217,
          "vwap": 220.4475,
          "label": "March 24, 25",
          "changeOverTime": -0.0012217
        },
        {
          "date": "2025-03-21",
          "open": 211.56,
          "high": 218.84,
          "low": 211.28,
          "close": 218.27,
          "adjClose": 217.98,
          "volume": 94127800,
          "unadjustedVolume": 94127800,
          "change": 6.71,
          "changePercent": 3.17,
          "vwap": 214.9875,

In [4]:
# Ensuring all the Stores' symbols are in the data requested
symbols_in_data = [stock['symbol'] for stock in data['historicalStockList']]
print(symbols_in_data)

['AAPL', 'GOOGL', 'MSFT', 'META']

In [5]:
renaming_symbols = {
    'GOOG': 'GOOGLE',
    'META': 'META',
    'AAPL': 'APPLE',
    'MSFT':'MICROSOFT'
}

renamed_symbols = [renaming_symbols.get(sym, sym) for sym in symbols_in_data]
print(renamed_symbols)

['APPLE', 'GOOGL', 'MICROSOFT', 'META']

In [6]:
# The data contains a list under 'historicalStockList'
all_data = []

for stock in data['historicalStockList']:
    symbol = stock['symbol']
    for daily_data in stock['historical']:
        daily_data['symbol'] = symbol  # Add stock symbol to each row
        all_data.append(daily_data)

# Convert to DataFrame
df = pd.DataFrame(all_data)

df['symbol'] = df['symbol'].replace(renaming_symbols) 


# Convert 'date' to datetime type
df['date'] = pd.to_datetime(df['date'])

# Sort for consistency in display
df = df.sort_values(by=['symbol', 'date']).reset_index(drop=True)


print(df)

          date    open    high       low   close  adjClose    volume  \
0   2024-05-30  190.76  192.18  190.6300  191.29    190.40  49947941
1   2024-05-31  191.44  192.57  189.9100  192.25    191.36  75158300
2   2024-06-03  192.90  194.99  192.5200  194.03    193.13  50080539
3   2024-06-04  194.64  195.32  193.0300  194.35    193.45  47471445
4   2024-06-05  195.40  196.90  194.8700  195.87    194.96  54156800
..         ...     ...     ...       ...     ...       ...       ...
995 2025-05-22  454.95  460.25  453.9000  454.86    454.86  18025612
996 2025-05-23  449.98  453.69  448.9100  450.18    450.18  16883509
997 2025-05-27  456.48  460.95  456.1200  460.69    460.69  20974300
998 2025-05-28  461.22  462.52  456.9300  457.36    457.36  17086261
999 2025-05-29  461.51  461.72  455.3105  458.86    458.86   5977993

     unadjustedVolume  change  changePercent      vwap        label  \
0            49947941   0.530       0.277840  191.2150   May 30, 24
1            75158300   0.810       0.423110  191.5425   May 31, 24
2            50080539   1.130       0.585800  193.6100  June 03, 24
3            47471445  -0.285      -0.148990  194.3350  June 04, 24
4            54156800   0.470       0.240530  195.7600  June 05, 24
..                ...     ...            ...       ...          ...
995          18025612  -0.090      -0.019782  455.9900   May 22, 25
996          16883509   0.200       0.044446  450.6900   May 23, 25
997          20974300   4.210       0.922270  458.5600   May 27, 25
998          17086261  -3.860      -0.836910  459.5075   May 28, 25
999           5977993  -2.650      -0.574202  458.6300   May 29, 25

     changeOverTime     symbol
0          0.002778      APPLE
1          0.004231      APPLE
2          0.005858      APPLE
3         -0.001490      APPLE
4          0.002405      APPLE
..              ...        ...
995       -0.000198  MICROSOFT
996        0.000444  MICROSOFT
997        0.009223  MICROSOFT
998       -0.008369  MICROSOFT
999       -0.005742  MICROSOFT

[1000 rows x 14 columns]

In [7]:
columns_of_interest = ['date', 'symbol', 'open', 'high', 'low', 'close', 
                       'adjClose', 'volume', 'unadjustedVolume', 
                       'change', 'changePercent', 'vwap', 
                       'label', 'changeOverTime']

# df with requested columns
df = df[columns_of_interest]
df

,date,symbol,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime
0,2024-05-30,APPLE,190.76,192.18,190.6300,191.29,190.40,49947941,49947941,0.530,0.277840,191.2150,"May 30, 24",0.002778
1,2024-05-31,APPLE,191.44,192.57,189.9100,192.25,191.36,75158300,75158300,0.810,0.423110,191.5425,"May 31, 24",0.004231
2,2024-06-03,APPLE,192.90,194.99,192.5200,194.03,193.13,50080539,50080539,1.130,0.585800,193.6100,"June 03, 24",0.005858
3,2024-06-04,APPLE,194.64,195.32,193.0300,194.35,193.45,47471445,47471445,-0.285,-0.148990,194.3350,"June 04, 24",-0.001490
4,2024-06-05,APPLE,195.40,196.90,194.8700,195.87,194.96,54156800,54156800,0.470,0.240530,195.7600,"June 05, 24",0.002405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2025-05-22,MICROSOFT,454.95,460.25,453.9000,454.86,454.86,18025612,18025612,-0.090,-0.019782,455.9900,"May 22, 25",-0.000198
996,2025-05-23,MICROSOFT,449.98,453.69,448.9100,450.18,450.18,16883509,16883509,0.200,0.044446,450.6900,"May 23, 25",0.000444
997,2025-05-27,MICROSOFT,456.48,460.95,456.1200,460.69,460.69,20974300,20974300,4.210,0.922270,458.5600,"May 27, 25",0.009223
998,2025-05-28,MICROSOFT,461.22,462.52,456.9300,457.36,457.36,17086261,17086261,-3.860,-0.836910,459.5075,"May 28, 25",-0.008369
999,2025-05-29,MICROSOFT,461.51,461.72,455.3105,458.86,458.86,5977993,5977993,-2.650,-0.574202,458.6300,"May 29, 25",-0.005742

In [8]:
df = df.dropna(how='all')  # Removing empty rows
df

,date,symbol,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime
0,2024-05-30,APPLE,190.76,192.18,190.6300,191.29,190.40,49947941,49947941,0.530,0.277840,191.2150,"May 30, 24",0.002778
1,2024-05-31,APPLE,191.44,192.57,189.9100,192.25,191.36,75158300,75158300,0.810,0.423110,191.5425,"May 31, 24",0.004231
2,2024-06-03,APPLE,192.90,194.99,192.5200,194.03,193.13,50080539,50080539,1.130,0.585800,193.6100,"June 03, 24",0.005858
3,2024-06-04,APPLE,194.64,195.32,193.0300,194.35,193.45,47471445,47471445,-0.285,-0.148990,194.3350,"June 04, 24",-0.001490
4,2024-06-05,APPLE,195.40,196.90,194.8700,195.87,194.96,54156800,54156800,0.470,0.240530,195.7600,"June 05, 24",0.002405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2025-05-22,MICROSOFT,454.95,460.25,453.9000,454.86,454.86,18025612,18025612,-0.090,-0.019782,455.9900,"May 22, 25",-0.000198
996,2025-05-23,MICROSOFT,449.98,453.69,448.9100,450.18,450.18,16883509,16883509,0.200,0.044446,450.6900,"May 23, 25",0.000444
997,2025-05-27,MICROSOFT,456.48,460.95,456.1200,460.69,460.69,20974300,20974300,4.210,0.922270,458.5600,"May 27, 25",0.009223
998,2025-05-28,MICROSOFT,461.22,462.52,456.9300,457.36,457.36,17086261,17086261,-3.860,-0.836910,459.5075,"May 28, 25",-0.008369
999,2025-05-29,MICROSOFT,461.51,461.72,455.3105,458.86,458.86,5977993,5977993,-2.650,-0.574202,458.6300,"May 29, 25",-0.005742

In [9]:
df = df.dropna(axis=1, how='all')  # Removing empty columns 
df

,date,symbol,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime
0,2024-05-30,APPLE,190.76,192.18,190.6300,191.29,190.40,49947941,49947941,0.530,0.277840,191.2150,"May 30, 24",0.002778
1,2024-05-31,APPLE,191.44,192.57,189.9100,192.25,191.36,75158300,75158300,0.810,0.423110,191.5425,"May 31, 24",0.004231
2,2024-06-03,APPLE,192.90,194.99,192.5200,194.03,193.13,50080539,50080539,1.130,0.585800,193.6100,"June 03, 24",0.005858
3,2024-06-04,APPLE,194.64,195.32,193.0300,194.35,193.45,47471445,47471445,-0.285,-0.148990,194.3350,"June 04, 24",-0.001490
4,2024-06-05,APPLE,195.40,196.90,194.8700,195.87,194.96,54156800,54156800,0.470,0.240530,195.7600,"June 05, 24",0.002405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2025-05-22,MICROSOFT,454.95,460.25,453.9000,454.86,454.86,18025612,18025612,-0.090,-0.019782,455.9900,"May 22, 25",-0.000198
996,2025-05-23,MICROSOFT,449.98,453.69,448.9100,450.18,450.18,16883509,16883509,0.200,0.044446,450.6900,"May 23, 25",0.000444
997,2025-05-27,MICROSOFT,456.48,460.95,456.1200,460.69,460.69,20974300,20974300,4.210,0.922270,458.5600,"May 27, 25",0.009223
998,2025-05-28,MICROSOFT,461.22,462.52,456.9300,457.36,457.36,17086261,17086261,-3.860,-0.836910,459.5075,"May 28, 25",-0.008369
999,2025-05-29,MICROSOFT,461.51,461.72,455.3105,458.86,458.86,5977993,5977993,-2.650,-0.574202,458.6300,"May 29, 25",-0.005742

In [10]:
df.isnull().sum().sum() # Checking is there is any empyty cell
df

,date,symbol,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime
0,2024-05-30,APPLE,190.76,192.18,190.6300,191.29,190.40,49947941,49947941,0.530,0.277840,191.2150,"May 30, 24",0.002778
1,2024-05-31,APPLE,191.44,192.57,189.9100,192.25,191.36,75158300,75158300,0.810,0.423110,191.5425,"May 31, 24",0.004231
2,2024-06-03,APPLE,192.90,194.99,192.5200,194.03,193.13,50080539,50080539,1.130,0.585800,193.6100,"June 03, 24",0.005858
3,2024-06-04,APPLE,194.64,195.32,193.0300,194.35,193.45,47471445,47471445,-0.285,-0.148990,194.3350,"June 04, 24",-0.001490
4,2024-06-05,APPLE,195.40,196.90,194.8700,195.87,194.96,54156800,54156800,0.470,0.240530,195.7600,"June 05, 24",0.002405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2025-05-22,MICROSOFT,454.95,460.25,453.9000,454.86,454.86,18025612,18025612,-0.090,-0.019782,455.9900,"May 22, 25",-0.000198
996,2025-05-23,MICROSOFT,449.98,453.69,448.9100,450.18,450.18,16883509,16883509,0.200,0.044446,450.6900,"May 23, 25",0.000444
997,2025-05-27,MICROSOFT,456.48,460.95,456.1200,460.69,460.69,20974300,20974300,4.210,0.922270,458.5600,"May 27, 25",0.009223
998,2025-05-28,MICROSOFT,461.22,462.52,456.9300,457.36,457.36,17086261,17086261,-3.860,-0.836910,459.5075,"May 28, 25",-0.008369
999,2025-05-29,MICROSOFT,461.51,461.72,455.3105,458.86,458.86,5977993,5977993,-2.650,-0.574202,458.6300,"May 29, 25",-0.005742

In [11]:
df.to_csv(r"C:\Users\LENOVO\SRAPPING\stock_data.csv", index=False)

In [12]:
df1 = pd.read_csv('stock_data.csv')
df1

,date,symbol,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime
0,2024-05-30,APPLE,190.76,192.18,190.6300,191.29,190.40,49947941,49947941,0.530,0.277840,191.2150,"May 30, 24",0.002778
1,2024-05-31,APPLE,191.44,192.57,189.9100,192.25,191.36,75158300,75158300,0.810,0.423110,191.5425,"May 31, 24",0.004231
2,2024-06-03,APPLE,192.90,194.99,192.5200,194.03,193.13,50080539,50080539,1.130,0.585800,193.6100,"June 03, 24",0.005858
3,2024-06-04,APPLE,194.64,195.32,193.0300,194.35,193.45,47471445,47471445,-0.285,-0.148990,194.3350,"June 04, 24",-0.001490
4,2024-06-05,APPLE,195.40,196.90,194.8700,195.87,194.96,54156800,54156800,0.470,0.240530,195.7600,"June 05, 24",0.002405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2025-05-22,MICROSOFT,454.95,460.25,453.9000,454.86,454.86,18025612,18025612,-0.090,-0.019782,455.9900,"May 22, 25",-0.000198
996,2025-05-23,MICROSOFT,449.98,453.69,448.9100,450.18,450.18,16883509,16883509,0.200,0.044446,450.6900,"May 23, 25",0.000444
997,2025-05-27,MICROSOFT,456.48,460.95,456.1200,460.69,460.69,20974300,20974300,4.210,0.922270,458.5600,"May 27, 25",0.009223
998,2025-05-28,MICROSOFT,461.22,462.52,456.9300,457.36,457.36,17086261,17086261,-3.860,-0.836910,459.5075,"May 28, 25",-0.008369
999,2025-05-29,MICROSOFT,461.51,461.72,455.3105,458.86,458.86,5977993,5977993,-2.650,-0.574202,458.6300,"May 29, 25",-0.005742